project_id = "zuurvqmbsfznrozcchpc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zuurvqmbsfznrozcchpc.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[functions.submit-contact]
verify_jwt = false

[functions.create-order]
verify_jwt = true