// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuurvqmbsfznrozcchpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1dXJ2cW1ic2Z6bnJvemNjaHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTk5ODcsImV4cCI6MjA3MjQ5NTk4N30.bSFAavbhUDujdsv83JstPjlom8sm1N_v65NAk2apEWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});